import type { Metadata } from "next";
import Providers from "@/src/lib/api/client/providers";
import Box from"@mui/material/Box";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
       <Providers>
        <Box sx={{height: "100vh"}}>{children}</Box></Providers> 
      </body>
    </html>
  );
}
